const data = [
    {
        id:1,
        img:'Data_Visualization.png',
        alt:"Data Visualization",
        description:"Developed using the MERN stack (MongoDB, Express.js, React.js, Node.js) with Chart.js for visualization, the Data Visualization App offers real-time data integration, allowing users to seamlessly add, update, and filter datasets with dynamic, live-updating visualizations. It features interactive charts, customizable visual elements, and responsive filtering for an enhanced data exploration experience.",
        title:"Data Visualization",
        url:'https://tusharmalhotra-datavisualization.vercel.app',
        status:"Completed",
    },
    {
        id:2,
        img: 'livechatapp.png',
        alt:"livechatappImg",
        description:"A live chat app facilitates real-time text-based communication between businesses and customers. It's a valuable tool for providing instant support, answering inquiries, and enhancing user engagement. These apps often include features like chatbots and conversation history tracking for efficiency and convenience.",
        title:"Live Chat Application",
        url:"https://tusharmalhotra-livechatapp.vercel.app",
        status:"Online",
    },
    {
        id:3,
        img: 'portfolio.png',
        alt:"PortfolioImg",
        description:"A portfolio is a collection of work or investments held by an individual or entity. It showcases their skills, experience, or financial holdings. Portfolios serve as a representation of accomplishments and can be used for various purposes, such as job applications or investment management.",
        title:"My Portfolio",
        url:"https://tusharmalhotra-portfolio.vercel.app",
        status:"Online",
    },
    {
        id:4,
        img: 'dashboard.png',
        alt:"Dashboard",
        description:"IT is a dashboard that can be used to display my front-end skills.",
        title:"Dashboard",
        url:"https://tusharmalhotra-vasitum-dashboard.vercel.app",
        status:"Online",
    },
    {
        id:5,
        img:'github-repo.png',
        alt:"Github Repo display",
        description:"This application can be used to display public repositories with paginations",
        title:"github-repo-display",
        url:'https://github-repo-display.vercel.app',
        status:"Completed",
    },
    {
        id:6,
        img:'TICTACTOEIMG.png',
        alt:"Tic Tac Toe Image",
        description:"Tic Tac Toe is a classic game played on a grid of 3x3 squares. Two players take turns marking X or O in empty squares with the objective of getting three of their symbols in a row, either horizontally, vertically, or diagonally. The game ends in a draw if all squares are filled without a winner.",
        title:"TIC TAC TOE",
        url:'https://github.com/TusharMalhotra11112/TICTACTOE',
        status:"Completed",
    },
]

export default data